apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipitsmarter-dotnet-example
  labels:
    {{- include "shipitsmarter-dotnet-example.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "shipitsmarter-dotnet-example.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shipitsmarter-dotnet-example.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SomeEnvValue
          value: "NiceValue"
        ports:
        - containerPort: 80
