name: Create simple-container
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository 🔎
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # https://github.com/docker/metadata-action#typesha
    # https://github.com/marketplace/actions/docker-metadata-action
    # https://thekevinwang.com/2022/06/13/github-actions-survival-skills/#iterating-quickly
    # Some extra change
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          # Configure a pr tag when this is a PR build, include both the number and the full sha
          type=raw,value=pr-${{ github.event.number }}-${{ github.event.pull_request.head.sha }},enable=${{ github.event_name == 'pull_request' }}
          # set latest tag for default branch
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./src
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - run: |
        echo "${JSON}" | jq
      env:
        JSON: ${{ toJson(steps.meta.outputs) }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ fromJson(steps.meta.outputs.json).tags[0] }}  # Take the first reference, and for some reason the normal tags is a single string with a \n in it (therefore I thought it was a list).
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Add preview label to pull request
      if: github.event_name == 'pull_request'
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: |
          preview
